### ISSUE TITLE
Do you plan to keep event copying?

### ISSUE THREAD

**Issue by howardroark** [yoshuawuyts/nanodiff#3]
Hey!

I am working with morphdom to build a backbone.js view extension. Because all events are discarded each time and I am morphing an element which is many views combined...  I have to get a bit creative.  I am writing some extra stuff to map all the events defined in each view to a central object to redistribute them after each render.   

I was just wondering if you plan to keep that addition? 

Thanks!

**Comment by yoshuawuyts** [comment]
Yeah def; it's necessary for the elements to work correctly I reckon - copied the code from https://github.com/maxogden/yo-yo/blob/master/index.js

**Comment by howardroark** [comment]
Great thanks!  Now I just need to find a cli tool that downloads node modules from GitHub and converts them to browser globals ;)  Or build it!
